name: Bug report
description: Report bugs with the recreation here
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug here."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Crash Log or System Log (if existing)"
      render: bash
    validations:
      required: false

  - type: textarea
    id: target
    attributes:
      label: "What platfrom and platform version are you playing on?"
      render: bash
    validations:
      required: true
