name: Bug report
description: Report bugs with the recreation here
labels: [bug]

body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug here."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Crash Log or System Log (if existing)"
      render: bash
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Windows
        - Linux
        - macOS
        - Android
        - iOS
    validations:
      required: true

  - type: input
    id: platform_details
    attributes:
      label: Platform Version / Edition
      description: |
        Examples:
        - Windows 11 Pro 25H2
        - Windows 10 Home 22H2
        - Arch Linux
        - Debian 13
        - macOS 15.7
        - Android 15
        - iOS 18.5
      placeholder: "Windows 11 Pro 25H2"
    validations:
      required: true
